schema_version = "1.0.0"

id = "hair_net"
version = "1.0.0"
name = "Hair Net"
tagline = "Converts mesh and curves into hair guides for the particle hair system"
maintainer = "Holo"
type = "add-on"
tags = ["Physics", "Pipeline"]

blender_version_min = "5.0.0"
# for earlier versions: https://github.com/Jandals/HairNet

# Updated docs: 

website = "https://github.com/HoloXXXX/HairNet"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]