schema_version = "1.0."

id = "hair_net"
version = "1.0.1"
name = "Hair Net"
tagline = "Converts mesh and curves into particle hair"
maintainer = "Holo"
type = "add-on"
tags = ["Physics", "Pipeline"]

blender_version_min = "5.0.0"
# for earlier versions: https://github.com/Jandals/HairNet

# Updated docs: 
website = "https://github.com/HoloXXXX/HairNet/blob/master/README.md"

license = [
  "SPDX:GPL-3.0-or-later",
]
